export const questiondata = {
  questions: [
    {
      category: 'Number Puzzles',
      id: 1,
      difficulty: 'Easy',
      question: 'What number should replace the question mark? 2, 4, 6, ?, 10',
      hint: "It's a simple addition pattern.",
      explanation: 'Each number increases by 2. The missing number is 8.',
      answer: 8,
    },
    {
      category: 'Number Puzzles',
      id: 2,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 5, 10, 15, 20, ?',
      hint: 'Each number increases by 5.',
      explanation:
        'The sequence increases by 5 each time. The next number is 25.',
      answer: 25,
    },
    {
      category: 'Number Puzzles',
      id: 3,
      difficulty: 'Medium',
      question: 'Find the missing number: 1, 3, 6, 10, ?, 21',
      hint: 'Look at the differences between consecutive numbers.',
      explanation:
        'The differences are 2, 3, 4, 5, etc. The missing number is 15.',
      answer: 15,
    },
    {
      category: 'Number Puzzles',
      id: 4,
      difficulty: 'Medium',
      question: 'What comes next in the sequence? 1, 4, 9, 16, 25, ?',
      hint: 'These are square numbers.',
      explanation:
        'The sequence represents squares of natural numbers: 1^2, 2^2, 3^2, etc. The next number is 36.',
      answer: 36,
    },
    {
      category: 'Number Puzzles',
      id: 5,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 1, 1, 2, 3, 5, 8, ?',
      hint: 'This is the Fibonacci sequence.',
      explanation:
        'Each number is the sum of the two preceding ones. The next number is 13.',
      answer: 13,
    },
    {
      category: 'Arithmetic Challenges',
      id: 6,
      difficulty: 'Easy',
      question: 'Solve: 10 - 4 × 2 = ?',
      hint: 'Use the order of operations (PEMDAS/BODMAS).',
      explanation:
        'Multiplication comes first: 4 × 2 = 8. Then subtract: 10 - 8 = 2.',
      answer: 2,
    },
    {
      category: 'Arithmetic Challenges',
      id: 7,
      difficulty: 'Easy',
      question: 'What is 12 ÷ 3 + 5?',
      hint: 'Perform division first.',
      explanation: '12 ÷ 3 = 4, then 4 + 5 = 9.',
      answer: 9,
    },
    {
      category: 'Arithmetic Challenges',
      id: 8,
      difficulty: 'Medium',
      question: 'Solve for x: 2x + 3 = 11',
      hint: 'Subtract 3 from both sides, then divide by 2.',
      explanation: '2x = 11 - 3, 2x = 8, x = 4.',
      answer: 4,
    },
    {
      category: 'Arithmetic Challenges',
      id: 9,
      difficulty: 'Medium',
      question: 'What is 15% of 200?',
      hint: 'Multiply 200 by 0.15.',
      explanation: '15% of 200 is 200 × 0.15 = 30.',
      answer: 30,
    },
    {
      category: 'Arithmetic Challenges',
      id: 10,
      difficulty: 'Hard',
      question: 'A train travels 300 km in 5 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 300 km ÷ 5 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Arithmetic Challenges',
      id: 11,
      difficulty: 'Hard',
      question: 'If 3x + 7 = 22, what is the value of x?',
      hint: 'Subtract 7 from both sides, then divide by 3.',
      explanation: '3x = 22 - 7, 3x = 15, x = 5.',
      answer: 5,
    },
    {
      category: 'Logic Puzzles',
      id: 12,
      difficulty: 'Easy',
      question:
        'If 5 cats catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?',
      hint: 'Think about the rate at which cats catch mice.',
      explanation:
        'Each cat catches 1 mouse in 5 minutes. So, 5 cats are needed to catch 100 mice in 100 minutes.',
      answer: 5,
    },
    {
      category: 'Logic Puzzles',
      id: 13,
      difficulty: 'Medium',
      question:
        'A clock shows 3:15. What is the angle between the hour and minute hands?',
      hint: 'Calculate the positions of the hour and minute hands.',
      explanation:
        'At 3:15, the minute hand is at 90 degrees, and the hour hand is at 97.5 degrees. The angle is 7.5 degrees.',
      answer: 7,
    },
    {
      category: 'Logic Puzzles',
      id: 14,
      difficulty: 'Hard',
      question: 'If 2^x = 16, what is the value of x?',
      hint: 'Express 16 as a power of 2.',
      explanation: '16 = 2^4, so x = 4.',
      answer: 4,
    },
    {
      category: 'Geometry',
      id: 15,
      difficulty: 'Easy',
      question: 'What is the perimeter of a square with side length 5?',
      hint: 'Perimeter of a square = 4 × side length.',
      explanation: 'Perimeter = 4 × 5 = 20.',
      answer: 20,
    },
    {
      category: 'Geometry',
      id: 16,
      difficulty: 'Medium',
      question: 'What is the area of a rectangle with length 8 and width 5?',
      hint: 'Area of a rectangle = length × width.',
      explanation: 'Area = 8 × 5 = 40.',
      answer: 40,
    },
    {
      category: 'Geometry',
      id: 17,
      difficulty: 'Hard',
      question: 'What is the volume of a cube with side length 3?',
      hint: 'Volume of a cube = side length^3.',
      explanation: 'Volume = 3^3 = 27.',
      answer: 27,
    },
    {
      category: 'Algebra',
      id: 18,
      difficulty: 'Easy',
      question: 'Solve for x: x + 5 = 12',
      hint: 'Subtract 5 from both sides.',
      explanation: 'x = 12 - 5, x = 7.',
      answer: 7,
    },
    {
      category: 'Algebra',
      id: 19,
      difficulty: 'Medium',
      question: 'Solve for x: 3x - 4 = 14',
      hint: 'Add 4 to both sides, then divide by 3.',
      explanation: '3x = 14 + 4, 3x = 18, x = 6.',
      answer: 6,
    },
    {
      category: 'Algebra',
      id: 20,
      difficulty: 'Hard',
      question: 'Solve for x: 2(x + 3) = 16',
      hint: 'Divide both sides by 2, then subtract 3.',
      explanation: 'x + 3 = 8, x = 8 - 3, x = 5.',
      answer: 5,
    },
    {
      category: 'Fractions',
      id: 21,
      difficulty: 'Easy',
      question: 'What is 1/2 of 10?',
      hint: 'Multiply 10 by 1/2.',
      explanation: '1/2 of 10 is 10 × 1/2 = 5.',
      answer: 5,
    },
    {
      category: 'Fractions',
      id: 22,
      difficulty: 'Medium',
      question: 'What is 3/4 of 20?',
      hint: 'Multiply 20 by 3/4.',
      explanation: '3/4 of 20 is 20 × 3/4 = 15.',
      answer: 15,
    },
    {
      category: 'Fractions',
      id: 23,
      difficulty: 'Hard',
      question: 'What is 5/6 of 36?',
      hint: 'Multiply 36 by 5/6.',
      explanation: '5/6 of 36 is 36 × 5/6 = 30.',
      answer: 30,
    },
    {
      category: 'Decimals',
      id: 24,
      difficulty: 'Easy',
      question: 'What is 0.5 × 10?',
      hint: 'Multiply 0.5 by 10.',
      explanation: '0.5 × 10 = 5.',
      answer: 5,
    },
    {
      category: 'Decimals',
      id: 25,
      difficulty: 'Medium',
      question: 'What is 0.25 × 16?',
      hint: 'Multiply 0.25 by 16.',
      explanation: '0.25 × 16 = 4.',
      answer: 4,
    },
    {
      category: 'Decimals',
      id: 26,
      difficulty: 'Hard',
      question: 'What is 0.75 × 24?',
      hint: 'Multiply 0.75 by 24.',
      explanation: '0.75 × 24 = 18.',
      answer: 18,
    },
    {
      category: 'Word Problems',
      id: 27,
      difficulty: 'Easy',
      question:
        'If a box contains 12 apples and you take out 4, how many apples are left?',
      hint: 'Subtract 4 from 12.',
      explanation: '12 - 4 = 8 apples are left.',
      answer: 8,
    },
    {
      category: 'Word Problems',
      id: 28,
      difficulty: 'Medium',
      question:
        'A pizza is divided into 8 slices. If you eat 3 slices, how many slices are left?',
      hint: 'Subtract 3 from 8.',
      explanation: '8 - 3 = 5 slices are left.',
      answer: 5,
    },
    {
      category: 'Word Problems',
      id: 29,
      difficulty: 'Hard',
      question:
        'A car travels 60 km in 1 hour. How far will it travel in 3 hours?',
      hint: 'Multiply 60 by 3.',
      explanation: '60 × 3 = 180 km.',
      answer: 180,
    },
    {
      category: 'Probability',
      id: 30,
      difficulty: 'Easy',
      question: 'What is the probability of rolling a 3 on a 6-sided die?',
      hint: 'There is 1 favorable outcome out of 6.',
      explanation: 'Probability = 1/6.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 31,
      difficulty: 'Medium',
      question:
        'What is the probability of rolling an even number on a 6-sided die?',
      hint: 'There are 3 even numbers (2, 4, 6) out of 6.',
      explanation: 'Probability = 3/6 = 1/2.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 32,
      difficulty: 'Hard',
      question:
        'What is the probability of drawing a red card from a standard deck of 52 cards?',
      hint: 'There are 26 red cards (hearts and diamonds) out of 52.',
      explanation: 'Probability = 26/52 = 1/2.',
      answer: 1,
    },
    {
      category: 'Number Puzzles',
      id: 33,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 10, 20, 30, 40, ?',
      hint: 'Each number increases by 10.',
      explanation:
        'The sequence increases by 10 each time. The next number is 50.',
      answer: 50,
    },
    {
      category: 'Number Puzzles',
      id: 34,
      difficulty: 'Medium',
      question: 'Find the missing number: 2, 4, 8, 16, ?, 64',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 2, 4, 8, 16, 32, 64. The missing number is 32.',
      answer: 32,
    },
    {
      category: 'Number Puzzles',
      id: 35,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 1, 3, 6, 10, 15, ?',
      hint: 'Look at the differences between consecutive numbers.',
      explanation:
        'The differences are 2, 3, 4, 5, etc. The next difference is 6, so the missing number is 21.',
      answer: 21,
    },
    {
      category: 'Arithmetic Challenges',
      id: 36,
      difficulty: 'Easy',
      question: 'What is 7 × 8?',
      hint: 'Multiply 7 by 8.',
      explanation: '7 × 8 = 56.',
      answer: 56,
    },
    {
      category: 'Arithmetic Challenges',
      id: 37,
      difficulty: 'Medium',
      question: 'What is 144 ÷ 12?',
      hint: 'Divide 144 by 12.',
      explanation: '144 ÷ 12 = 12.',
      answer: 12,
    },
    {
      category: 'Arithmetic Challenges',
      id: 38,
      difficulty: 'Hard',
      question: 'What is 25% of 80?',
      hint: 'Multiply 80 by 0.25.',
      explanation: '25% of 80 is 80 × 0.25 = 20.',
      answer: 20,
    },
    {
      category: 'Logic Puzzles',
      id: 39,
      difficulty: 'Easy',
      question: 'If 3 pencils cost $6, how much does 1 pencil cost?',
      hint: 'Divide the total cost by the number of pencils.',
      explanation: '6 ÷ 3 = $2 per pencil.',
      answer: 2,
    },
    {
      category: 'Logic Puzzles',
      id: 40,
      difficulty: 'Medium',
      question:
        'If 4 workers can build a wall in 10 days, how many days will it take 5 workers to build the same wall?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '4 workers × 10 days = 5 workers × x days. x = 8 days.',
      answer: 8,
    },
    {
      category: 'Logic Puzzles',
      id: 41,
      difficulty: 'Hard',
      question: 'If 2^x = 32, what is the value of x?',
      hint: 'Express 32 as a power of 2.',
      explanation: '32 = 2^5, so x = 5.',
      answer: 5,
    },
    {
      category: 'Geometry',
      id: 42,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 7?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 7^2 = 49.',
      answer: 49,
    },
    {
      category: 'Geometry',
      id: 43,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 7? (Use π = 22/7)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × (22/7) × 7 = 44.',
      answer: 44,
    },
    {
      category: 'Geometry',
      id: 44,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 10 and height 5?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (10 × 5) ÷ 2 = 25.',
      answer: 25,
    },
    {
      category: 'Algebra',
      id: 45,
      difficulty: 'Easy',
      question: 'Solve for x: x - 4 = 10',
      hint: 'Add 4 to both sides.',
      explanation: 'x = 10 + 4, x = 14.',
      answer: 14,
    },
    {
      category: 'Algebra',
      id: 46,
      difficulty: 'Medium',
      question: 'Solve for x: 5x + 10 = 35',
      hint: 'Subtract 10 from both sides, then divide by 5.',
      explanation: '5x = 35 - 10, 5x = 25, x = 5.',
      answer: 5,
    },
    {
      category: 'Algebra',
      id: 47,
      difficulty: 'Hard',
      question: 'Solve for x: 4(x - 2) = 20',
      hint: 'Divide both sides by 4, then add 2.',
      explanation: 'x - 2 = 5, x = 5 + 2, x = 7.',
      answer: 7,
    },
    {
      category: 'Fractions',
      id: 48,
      difficulty: 'Easy',
      question: 'What is 1/4 of 20?',
      hint: 'Multiply 20 by 1/4.',
      explanation: '1/4 of 20 is 20 × 1/4 = 5.',
      answer: 5,
    },
    {
      category: 'Fractions',
      id: 49,
      difficulty: 'Medium',
      question: 'What is 2/3 of 18?',
      hint: 'Multiply 18 by 2/3.',
      explanation: '2/3 of 18 is 18 × 2/3 = 12.',
      answer: 12,
    },
    {
      category: 'Fractions',
      id: 50,
      difficulty: 'Hard',
      question: 'What is 7/8 of 32?',
      hint: 'Multiply 32 by 7/8.',
      explanation: '7/8 of 32 is 32 × 7/8 = 28.',
      answer: 28,
    },
    {
      category: 'Decimals',
      id: 51,
      difficulty: 'Easy',
      question: 'What is 0.2 × 50?',
      hint: 'Multiply 0.2 by 50.',
      explanation: '0.2 × 50 = 10.',
      answer: 10,
    },
    {
      category: 'Decimals',
      id: 52,
      difficulty: 'Medium',
      question: 'What is 0.6 × 25?',
      hint: 'Multiply 0.6 by 25.',
      explanation: '0.6 × 25 = 15.',
      answer: 15,
    },
    {
      category: 'Decimals',
      id: 53,
      difficulty: 'Hard',
      question: 'What is 0.125 × 64?',
      hint: 'Multiply 0.125 by 64.',
      explanation: '0.125 × 64 = 8.',
      answer: 8,
    },
    {
      category: 'Word Problems',
      id: 54,
      difficulty: 'Easy',
      question:
        'If a book has 200 pages and you read 50 pages, how many pages are left?',
      hint: 'Subtract 50 from 200.',
      explanation: '200 - 50 = 150 pages are left.',
      answer: 150,
    },
    {
      category: 'Word Problems',
      id: 55,
      difficulty: 'Medium',
      question: 'A train travels 120 km in 2 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 120 km ÷ 2 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Word Problems',
      id: 56,
      difficulty: 'Hard',
      question:
        'A rectangle has a length of 12 and a width of 5. What is its perimeter?',
      hint: 'Perimeter = 2 × (length + width).',
      explanation: 'Perimeter = 2 × (12 + 5) = 34.',
      answer: 34,
    },
    {
      category: 'Probability',
      id: 57,
      difficulty: 'Easy',
      question: 'What is the probability of flipping heads on a fair coin?',
      hint: 'There is 1 favorable outcome out of 2.',
      explanation: 'Probability = 1/2.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 58,
      difficulty: 'Medium',
      question:
        'What is the probability of drawing a spade from a standard deck of 52 cards?',
      hint: 'There are 13 spades out of 52.',
      explanation: 'Probability = 13/52 = 1/4.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 59,
      difficulty: 'Hard',
      question:
        'What is the probability of rolling a prime number on a 6-sided die?',
      hint: 'Prime numbers on a die are 2, 3, and 5.',
      explanation: 'Probability = 3/6 = 1/2.',
      answer: 1,
    },
    {
      category: 'Number Puzzles',
      id: 60,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 3, 6, 9, 12, ?',
      hint: 'Each number increases by 3.',
      explanation:
        'The sequence increases by 3 each time. The next number is 15.',
      answer: 15,
    },
    {
      category: 'Number Puzzles',
      id: 61,
      difficulty: 'Medium',
      question: 'Find the missing number: 5, 10, 20, 40, ?, 160',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 5, 10, 20, 40, 80, 160. The missing number is 80.',
      answer: 80,
    },
    {
      category: 'Number Puzzles',
      id: 62,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 2, 5, 10, 17, 26, ?',
      hint: 'Look at the differences between consecutive numbers.',
      explanation:
        'The differences are 3, 5, 7, 9, etc. The next difference is 11, so the missing number is 37.',
      answer: 37,
    },
    {
      category: 'Arithmetic Challenges',
      id: 63,
      difficulty: 'Easy',
      question: 'What is 9 × 7?',
      hint: 'Multiply 9 by 7.',
      explanation: '9 × 7 = 63.',
      answer: 63,
    },
    {
      category: 'Arithmetic Challenges',
      id: 64,
      difficulty: 'Medium',
      question: 'What is 169 ÷ 13?',
      hint: 'Divide 169 by 13.',
      explanation: '169 ÷ 13 = 13.',
      answer: 13,
    },
    {
      category: 'Arithmetic Challenges',
      id: 65,
      difficulty: 'Hard',
      question: 'What is 30% of 150?',
      hint: 'Multiply 150 by 0.30.',
      explanation: '30% of 150 is 150 × 0.30 = 45.',
      answer: 45,
    },
    {
      category: 'Logic Puzzles',
      id: 66,
      difficulty: 'Easy',
      question: 'If 4 apples cost $8, how much does 1 apple cost?',
      hint: 'Divide the total cost by the number of apples.',
      explanation: '8 ÷ 4 = $2 per apple.',
      answer: 2,
    },
    {
      category: 'Logic Puzzles',
      id: 67,
      difficulty: 'Medium',
      question:
        'If 6 workers can build a house in 12 days, how many days will it take 8 workers to build the same house?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '6 workers × 12 days = 8 workers × x days. x = 9 days.',
      answer: 9,
    },
    {
      category: 'Logic Puzzles',
      id: 68,
      difficulty: 'Hard',
      question: 'If 3^x = 81, what is the value of x?',
      hint: 'Express 81 as a power of 3.',
      explanation: '81 = 3^4, so x = 4.',
      answer: 4,
    },
    {
      category: 'Geometry',
      id: 69,
      difficulty: 'Easy',
      question: 'What is the area of a rectangle with length 9 and width 4?',
      hint: 'Area of a rectangle = length × width.',
      explanation: 'Area = 9 × 4 = 36.',
      answer: 36,
    },
    {
      category: 'Geometry',
      id: 70,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 14? (Use π = 22/7)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × (22/7) × 14 = 88.',
      answer: 88,
    },
    {
      category: 'Geometry',
      id: 71,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 12 and height 6?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (12 × 6) ÷ 2 = 36.',
      answer: 36,
    },
    {
      category: 'Algebra',
      id: 72,
      difficulty: 'Easy',
      question: 'Solve for x: x + 7 = 15',
      hint: 'Subtract 7 from both sides.',
      explanation: 'x = 15 - 7, x = 8.',
      answer: 8,
    },
    {
      category: 'Algebra',
      id: 73,
      difficulty: 'Medium',
      question: 'Solve for x: 6x - 12 = 24',
      hint: 'Add 12 to both sides, then divide by 6.',
      explanation: '6x = 24 + 12, 6x = 36, x = 6.',
      answer: 6,
    },
    {
      category: 'Algebra',
      id: 74,
      difficulty: 'Hard',
      question: 'Solve for x: 5(x - 3) = 25',
      hint: 'Divide both sides by 5, then add 3.',
      explanation: 'x - 3 = 5, x = 5 + 3, x = 8.',
      answer: 8,
    },
    {
      category: 'Fractions',
      id: 75,
      difficulty: 'Easy',
      question: 'What is 1/5 of 25?',
      hint: 'Multiply 25 by 1/5.',
      explanation: '1/5 of 25 is 25 × 1/5 = 5.',
      answer: 5,
    },
    {
      category: 'Fractions',
      id: 76,
      difficulty: 'Medium',
      question: 'What is 3/5 of 50?',
      hint: 'Multiply 50 by 3/5.',
      explanation: '3/5 of 50 is 50 × 3/5 = 30.',
      answer: 30,
    },
    {
      category: 'Fractions',
      id: 77,
      difficulty: 'Hard',
      question: 'What is 5/6 of 72?',
      hint: 'Multiply 72 by 5/6.',
      explanation: '5/6 of 72 is 72 × 5/6 = 60.',
      answer: 60,
    },
    {
      category: 'Decimals',
      id: 78,
      difficulty: 'Easy',
      question: 'What is 0.3 × 40?',
      hint: 'Multiply 0.3 by 40.',
      explanation: '0.3 × 40 = 12.',
      answer: 12,
    },
    {
      category: 'Decimals',
      id: 79,
      difficulty: 'Medium',
      question: 'What is 0.7 × 30?',
      hint: 'Multiply 0.7 by 30.',
      explanation: '0.7 × 30 = 21.',
      answer: 21,
    },
    {
      category: 'Decimals',
      id: 80,
      difficulty: 'Hard',
      question: 'What is 0.0625 × 80?',
      hint: 'Multiply 0.0625 by 80.',
      explanation: '0.0625 × 80 = 5.',
      answer: 5,
    },
    {
      category: 'Word Problems',
      id: 81,
      difficulty: 'Easy',
      question:
        'If a box contains 24 chocolates and you eat 6, how many chocolates are left?',
      hint: 'Subtract 6 from 24.',
      explanation: '24 - 6 = 18 chocolates are left.',
      answer: 18,
    },
    {
      category: 'Word Problems',
      id: 82,
      difficulty: 'Medium',
      question: 'A car travels 180 km in 3 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 180 km ÷ 3 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Word Problems',
      id: 83,
      difficulty: 'Hard',
      question:
        'A rectangle has a length of 15 and a width of 6. What is its perimeter?',
      hint: 'Perimeter = 2 × (length + width).',
      explanation: 'Perimeter = 2 × (15 + 6) = 42.',
      answer: 42,
    },
    {
      category: 'Probability',
      id: 84,
      difficulty: 'Easy',
      question: 'What is the probability of rolling a 6 on a 6-sided die?',
      hint: 'There is 1 favorable outcome out of 6.',
      explanation: 'Probability = 1/6.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 85,
      difficulty: 'Medium',
      question:
        'What is the probability of drawing a heart from a standard deck of 52 cards?',
      hint: 'There are 13 hearts out of 52.',
      explanation: 'Probability = 13/52 = 1/4.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 86,
      difficulty: 'Hard',
      question:
        'What is the probability of rolling a number greater than 4 on a 6-sided die?',
      hint: 'Favorable outcomes are 5 and 6.',
      explanation: 'Probability = 2/6 = 1/3.',
      answer: 1,
    },
    {
      category: 'Number Puzzles',
      id: 87,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 4, 8, 12, 16, ?',
      hint: 'Each number increases by 4.',
      explanation:
        'The sequence increases by 4 each time. The next number is 20.',
      answer: 20,
    },
    {
      category: 'Number Puzzles',
      id: 88,
      difficulty: 'Medium',
      question: 'Find the missing number: 7, 14, 28, 56, ?, 224',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 7, 14, 28, 56, 112, 224. The missing number is 112.',
      answer: 112,
    },
    {
      category: 'Number Puzzles',
      id: 89,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 3, 9, 27, 81, ?',
      hint: 'Each number is multiplied by 3.',
      explanation: 'The sequence is 3, 9, 27, 81, 243. The next number is 243.',
      answer: 243,
    },
    {
      category: 'Arithmetic Challenges',
      id: 90,
      difficulty: 'Easy',
      question: 'What is 8 × 9?',
      hint: 'Multiply 8 by 9.',
      explanation: '8 × 9 = 72.',
      answer: 72,
    },
    {
      category: 'Arithmetic Challenges',
      id: 91,
      difficulty: 'Medium',
      question: 'What is 225 ÷ 15?',
      hint: 'Divide 225 by 15.',
      explanation: '225 ÷ 15 = 15.',
      answer: 15,
    },
    {
      category: 'Arithmetic Challenges',
      id: 92,
      difficulty: 'Hard',
      question: 'What is 40% of 250?',
      hint: 'Multiply 250 by 0.40.',
      explanation: '40% of 250 is 250 × 0.40 = 100.',
      answer: 100,
    },
    {
      category: 'Logic Puzzles',
      id: 93,
      difficulty: 'Easy',
      question: 'If 5 oranges cost $10, how much does 1 orange cost?',
      hint: 'Divide the total cost by the number of oranges.',
      explanation: '10 ÷ 5 = $2 per orange.',
      answer: 2,
    },
    {
      category: 'Logic Puzzles',
      id: 94,
      difficulty: 'Medium',
      question:
        'If 8 workers can build a wall in 6 days, how many days will it take 12 workers to build the same wall?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '8 workers × 6 days = 12 workers × x days. x = 4 days.',
      answer: 4,
    },
    {
      category: 'Logic Puzzles',
      id: 95,
      difficulty: 'Hard',
      question: 'If 4^x = 256, what is the value of x?',
      hint: 'Express 256 as a power of 4.',
      explanation: '256 = 4^4, so x = 4.',
      answer: 4,
    },
    {
      category: 'Geometry',
      id: 96,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 10?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 10^2 = 100.',
      answer: 100,
    },
    {
      category: 'Geometry',
      id: 97,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 21? (Use π = 22/7)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × (22/7) × 21 = 132.',
      answer: 132,
    },
    {
      category: 'Geometry',
      id: 98,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 14 and height 7?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (14 × 7) ÷ 2 = 49.',
      answer: 49,
    },
    {
      category: 'Algebra',
      id: 99,
      difficulty: 'Easy',
      question: 'Solve for x: x + 9 = 18',
      hint: 'Subtract 9 from both sides.',
      explanation: 'x = 18 - 9, x = 9.',
      answer: 9,
    },
    {
      category: 'Algebra',
      id: 100,
      difficulty: 'Medium',
      question: 'Solve for x: 7x - 14 = 28',
      hint: 'Add 14 to both sides, then divide by 7.',
      explanation: '7x = 28 + 14, 7x = 42, x = 6.',
      answer: 6,
    },
    {
      category: 'Number Puzzles',
      id: 101,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 7, 14, 21, 28, ?',
      hint: 'Each number increases by 7.',
      explanation:
        'The sequence increases by 7 each time. The next number is 35.',
      answer: 35,
    },
    {
      category: 'Number Puzzles',
      id: 102,
      difficulty: 'Easy',
      question:
        'What number should replace the question mark? 10, 20, 30, ?, 50',
      hint: 'Each number increases by 10.',
      explanation:
        'The sequence increases by 10 each time. The missing number is 40.',
      answer: 40,
    },
    {
      category: 'Number Puzzles',
      id: 103,
      difficulty: 'Medium',
      question: 'Find the missing number: 2, 6, 18, 54, ?',
      hint: 'Each number is multiplied by 3.',
      explanation:
        'The sequence is 2, 6, 18, 54, 162. The missing number is 162.',
      answer: 162,
    },
    {
      category: 'Number Puzzles',
      id: 104,
      difficulty: 'Medium',
      question: 'What is the next number in the sequence? 1, 2, 4, 8, 16, ?',
      hint: 'Each number is multiplied by 2.',
      explanation: 'The sequence is 1, 2, 4, 8, 16, 32. The next number is 32.',
      answer: 32,
    },
    {
      category: 'Number Puzzles',
      id: 105,
      difficulty: 'Hard',
      question:
        'What is the next number in the sequence? 1, 4, 9, 16, 25, 36, ?',
      hint: 'These are square numbers.',
      explanation:
        'The sequence represents squares of natural numbers: 1^2, 2^2, 3^2, etc. The next number is 49.',
      answer: 49,
    },
    {
      category: 'Arithmetic Challenges',
      id: 106,
      difficulty: 'Easy',
      question: 'What is 6 × 7?',
      hint: 'Multiply 6 by 7.',
      explanation: '6 × 7 = 42.',
      answer: 42,
    },
    {
      category: 'Arithmetic Challenges',
      id: 107,
      difficulty: 'Easy',
      question: 'What is 144 ÷ 12?',
      hint: 'Divide 144 by 12.',
      explanation: '144 ÷ 12 = 12.',
      answer: 12,
    },
    {
      category: 'Arithmetic Challenges',
      id: 108,
      difficulty: 'Medium',
      question: 'What is 20% of 150?',
      hint: 'Multiply 150 by 0.20.',
      explanation: '20% of 150 is 150 × 0.20 = 30.',
      answer: 30,
    },
    {
      category: 'Arithmetic Challenges',
      id: 109,
      difficulty: 'Medium',
      question: 'What is 25 × 4?',
      hint: 'Multiply 25 by 4.',
      explanation: '25 × 4 = 100.',
      answer: 100,
    },
    {
      category: 'Arithmetic Challenges',
      id: 110,
      difficulty: 'Hard',
      question: 'What is 15% of 300?',
      hint: 'Multiply 300 by 0.15.',
      explanation: '15% of 300 is 300 × 0.15 = 45.',
      answer: 45,
    },
    {
      category: 'Logic Puzzles',
      id: 111,
      difficulty: 'Easy',
      question: 'If 3 pencils cost $9, how much does 1 pencil cost?',
      hint: 'Divide the total cost by the number of pencils.',
      explanation: '9 ÷ 3 = $3 per pencil.',
      answer: 3,
    },
    {
      category: 'Logic Puzzles',
      id: 112,
      difficulty: 'Medium',
      question:
        'If 5 workers can build a wall in 10 days, how many days will it take 10 workers to build the same wall?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '5 workers × 10 days = 10 workers × x days. x = 5 days.',
      answer: 5,
    },
    {
      category: 'Logic Puzzles',
      id: 113,
      difficulty: 'Hard',
      question: 'If 2^x = 64, what is the value of x?',
      hint: 'Express 64 as a power of 2.',
      explanation: '64 = 2^6, so x = 6.',
      answer: 6,
    },
    {
      category: 'Geometry',
      id: 114,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 6?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 6^2 = 36.',
      answer: 36,
    },
    {
      category: 'Geometry',
      id: 115,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 10? (Use π = 3.14)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × 3.14 × 10 = 62.8.',
      answer: 62,
    },
    {
      category: 'Geometry',
      id: 116,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 8 and height 5?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (8 × 5) ÷ 2 = 20.',
      answer: 20,
    },
    {
      category: 'Algebra',
      id: 117,
      difficulty: 'Easy',
      question: 'Solve for x: x + 8 = 20',
      hint: 'Subtract 8 from both sides.',
      explanation: 'x = 20 - 8, x = 12.',
      answer: 12,
    },
    {
      category: 'Algebra',
      id: 118,
      difficulty: 'Medium',
      question: 'Solve for x: 4x - 8 = 16',
      hint: 'Add 8 to both sides, then divide by 4.',
      explanation: '4x = 16 + 8, 4x = 24, x = 6.',
      answer: 6,
    },
    {
      category: 'Algebra',
      id: 119,
      difficulty: 'Hard',
      question: 'Solve for x: 3(x - 4) = 21',
      hint: 'Divide both sides by 3, then add 4.',
      explanation: 'x - 4 = 7, x = 7 + 4, x = 11.',
      answer: 11,
    },
    {
      category: 'Fractions',
      id: 120,
      difficulty: 'Easy',
      question: 'What is 1/3 of 21?',
      hint: 'Multiply 21 by 1/3.',
      explanation: '1/3 of 21 is 21 × 1/3 = 7.',
      answer: 7,
    },
    {
      category: 'Fractions',
      id: 121,
      difficulty: 'Medium',
      question: 'What is 2/5 of 50?',
      hint: 'Multiply 50 by 2/5.',
      explanation: '2/5 of 50 is 50 × 2/5 = 20.',
      answer: 20,
    },
    {
      category: 'Fractions',
      id: 122,
      difficulty: 'Hard',
      question: 'What is 3/4 of 80?',
      hint: 'Multiply 80 by 3/4.',
      explanation: '3/4 of 80 is 80 × 3/4 = 60.',
      answer: 60,
    },
    {
      category: 'Decimals',
      id: 123,
      difficulty: 'Easy',
      question: 'What is 0.4 × 25?',
      hint: 'Multiply 0.4 by 25.',
      explanation: '0.4 × 25 = 10.',
      answer: 10,
    },
    {
      category: 'Decimals',
      id: 124,
      difficulty: 'Medium',
      question: 'What is 0.8 × 15?',
      hint: 'Multiply 0.8 by 15.',
      explanation: '0.8 × 15 = 12.',
      answer: 12,
    },
    {
      category: 'Decimals',
      id: 125,
      difficulty: 'Hard',
      question: 'What is 0.125 × 80?',
      hint: 'Multiply 0.125 by 80.',
      explanation: '0.125 × 80 = 10.',
      answer: 10,
    },
    {
      category: 'Word Problems',
      id: 126,
      difficulty: 'Easy',
      question:
        'If a box contains 30 candies and you eat 10, how many candies are left?',
      hint: 'Subtract 10 from 30.',
      explanation: '30 - 10 = 20 candies are left.',
      answer: 20,
    },
    {
      category: 'Word Problems',
      id: 127,
      difficulty: 'Medium',
      question: 'A car travels 240 km in 4 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 240 km ÷ 4 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Word Problems',
      id: 128,
      difficulty: 'Hard',
      question:
        'A rectangle has a length of 18 and a width of 4. What is its perimeter?',
      hint: 'Perimeter = 2 × (length + width).',
      explanation: 'Perimeter = 2 × (18 + 4) = 44.',
      answer: 44,
    },
    {
      category: 'Probability',
      id: 129,
      difficulty: 'Easy',
      question: 'What is the probability of rolling a 2 on a 6-sided die?',
      hint: 'There is 1 favorable outcome out of 6.',
      explanation: 'Probability = 1/6.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 130,
      difficulty: 'Medium',
      question:
        'What is the probability of drawing a diamond from a standard deck of 52 cards?',
      hint: 'There are 13 diamonds out of 52.',
      explanation: 'Probability = 13/52 = 1/4.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 131,
      difficulty: 'Hard',
      question:
        'What is the probability of rolling a number less than 3 on a 6-sided die?',
      hint: 'Favorable outcomes are 1 and 2.',
      explanation: 'Probability = 2/6 = 1/3.',
      answer: 1,
    },
    {
      category: 'Number Puzzles',
      id: 132,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 9, 18, 27, 36, ?',
      hint: 'Each number increases by 9.',
      explanation:
        'The sequence increases by 9 each time. The next number is 45.',
      answer: 45,
    },
    {
      category: 'Number Puzzles',
      id: 133,
      difficulty: 'Medium',
      question: 'Find the missing number: 3, 9, 27, 81, ?',
      hint: 'Each number is multiplied by 3.',
      explanation:
        'The sequence is 3, 9, 27, 81, 243. The missing number is 243.',
      answer: 243,
    },
    {
      category: 'Number Puzzles',
      id: 134,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 2, 4, 8, 16, 32, ?',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 2, 4, 8, 16, 32, 64. The next number is 64.',
      answer: 64,
    },
    {
      category: 'Arithmetic Challenges',
      id: 135,
      difficulty: 'Easy',
      question: 'What is 7 × 9?',
      hint: 'Multiply 7 by 9.',
      explanation: '7 × 9 = 63.',
      answer: 63,
    },
    {
      category: 'Arithmetic Challenges',
      id: 136,
      difficulty: 'Medium',
      question: 'What is 256 ÷ 16?',
      hint: 'Divide 256 by 16.',
      explanation: '256 ÷ 16 = 16.',
      answer: 16,
    },
    {
      category: 'Arithmetic Challenges',
      id: 137,
      difficulty: 'Hard',
      question: 'What is 35% of 200?',
      hint: 'Multiply 200 by 0.35.',
      explanation: '35% of 200 is 200 × 0.35 = 70.',
      answer: 70,
    },
    {
      category: 'Logic Puzzles',
      id: 138,
      difficulty: 'Easy',
      question: 'If 4 apples cost $12, how much does 1 apple cost?',
      hint: 'Divide the total cost by the number of apples.',
      explanation: '12 ÷ 4 = $3 per apple.',
      answer: 3,
    },
    {
      category: 'Logic Puzzles',
      id: 139,
      difficulty: 'Medium',
      question:
        'If 6 workers can build a house in 18 days, how many days will it take 9 workers to build the same house?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '6 workers × 18 days = 9 workers × x days. x = 12 days.',
      answer: 12,
    },
    {
      category: 'Logic Puzzles',
      id: 140,
      difficulty: 'Hard',
      question: 'If 5^x = 125, what is the value of x?',
      hint: 'Express 125 as a power of 5.',
      explanation: '125 = 5^3, so x = 3.',
      answer: 3,
    },
    {
      category: 'Geometry',
      id: 141,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 8?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 8^2 = 64.',
      answer: 64,
    },
    {
      category: 'Geometry',
      id: 142,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 12? (Use π = 3.14)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × 3.14 × 12 = 75.36.',
      answer: 75,
    },
    {
      category: 'Geometry',
      id: 143,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 10 and height 8?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (10 × 8) ÷ 2 = 40.',
      answer: 40,
    },
    {
      category: 'Algebra',
      id: 144,
      difficulty: 'Easy',
      question: 'Solve for x: x + 10 = 25',
      hint: 'Subtract 10 from both sides.',
      explanation: 'x = 25 - 10, x = 15.',
      answer: 15,
    },
    {
      category: 'Algebra',
      id: 145,
      difficulty: 'Medium',
      question: 'Solve for x: 5x - 15 = 30',
      hint: 'Add 15 to both sides, then divide by 5.',
      explanation: '5x = 30 + 15, 5x = 45, x = 9.',
      answer: 9,
    },
    {
      category: 'Algebra',
      id: 146,
      difficulty: 'Hard',
      question: 'Solve for x: 4(x - 5) = 36',
      hint: 'Divide both sides by 4, then add 5.',
      explanation: 'x - 5 = 9, x = 9 + 5, x = 14.',
      answer: 14,
    },
    {
      category: 'Fractions',
      id: 147,
      difficulty: 'Easy',
      question: 'What is 1/4 of 24?',
      hint: 'Multiply 24 by 1/4.',
      explanation: '1/4 of 24 is 24 × 1/4 = 6.',
      answer: 6,
    },
    {
      category: 'Fractions',
      id: 148,
      difficulty: 'Medium',
      question: 'What is 3/5 of 60?',
      hint: 'Multiply 60 by 3/5.',
      explanation: '3/5 of 60 is 60 × 3/5 = 36.',
      answer: 36,
    },
    {
      category: 'Fractions',
      id: 149,
      difficulty: 'Hard',
      question: 'What is 5/6 of 90?',
      hint: 'Multiply 90 by 5/6.',
      explanation: '5/6 of 90 is 90 × 5/6 = 75.',
      answer: 75,
    },
    {
      category: 'Decimals',
      id: 150,
      difficulty: 'Easy',
      question: 'What is 0.5 × 40?',
      hint: 'Multiply 0.5 by 40.',
      explanation: '0.5 × 40 = 20.',
      answer: 20,
    },
    {
      category: 'Decimals',
      id: 151,
      difficulty: 'Medium',
      question: 'What is 0.75 × 20?',
      hint: 'Multiply 0.75 by 20.',
      explanation: '0.75 × 20 = 15.',
      answer: 15,
    },
    {
      category: 'Decimals',
      id: 152,
      difficulty: 'Hard',
      question: 'What is 0.0625 × 160?',
      hint: 'Multiply 0.0625 by 160.',
      explanation: '0.0625 × 160 = 10.',
      answer: 10,
    },
    {
      category: 'Word Problems',
      id: 153,
      difficulty: 'Easy',
      question:
        'If a box contains 40 chocolates and you eat 15, how many chocolates are left?',
      hint: 'Subtract 15 from 40.',
      explanation: '40 - 15 = 25 chocolates are left.',
      answer: 25,
    },
    {
      category: 'Word Problems',
      id: 154,
      difficulty: 'Medium',
      question: 'A car travels 300 km in 5 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 300 km ÷ 5 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Word Problems',
      id: 155,
      difficulty: 'Hard',
      question:
        'A rectangle has a length of 20 and a width of 5. What is its perimeter?',
      hint: 'Perimeter = 2 × (length + width).',
      explanation: 'Perimeter = 2 × (20 + 5) = 50.',
      answer: 50,
    },
    {
      category: 'Probability',
      id: 156,
      difficulty: 'Easy',
      question: 'What is the probability of rolling a 4 on a 6-sided die?',
      hint: 'There is 1 favorable outcome out of 6.',
      explanation: 'Probability = 1/6.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 157,
      difficulty: 'Medium',
      question:
        'What is the probability of drawing a club from a standard deck of 52 cards?',
      hint: 'There are 13 clubs out of 52.',
      explanation: 'Probability = 13/52 = 1/4.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 158,
      difficulty: 'Hard',
      question:
        'What is the probability of rolling a number greater than 2 on a 6-sided die?',
      hint: 'Favorable outcomes are 3, 4, 5, and 6.',
      explanation: 'Probability = 4/6 = 2/3.',
      answer: 2,
    },
    {
      category: 'Number Puzzles',
      id: 159,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 11, 22, 33, 44, ?',
      hint: 'Each number increases by 11.',
      explanation:
        'The sequence increases by 11 each time. The next number is 55.',
      answer: 55,
    },
    {
      category: 'Number Puzzles',
      id: 160,
      difficulty: 'Medium',
      question: 'Find the missing number: 4, 12, 36, 108, ?',
      hint: 'Each number is multiplied by 3.',
      explanation:
        'The sequence is 4, 12, 36, 108, 324. The missing number is 324.',
      answer: 324,
    },
    {
      category: 'Number Puzzles',
      id: 161,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 3, 6, 12, 24, 48, ?',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 3, 6, 12, 24, 48, 96. The next number is 96.',
      answer: 96,
    },
    {
      category: 'Arithmetic Challenges',
      id: 162,
      difficulty: 'Easy',
      question: 'What is 8 × 7?',
      hint: 'Multiply 8 by 7.',
      explanation: '8 × 7 = 56.',
      answer: 56,
    },
    {
      category: 'Arithmetic Challenges',
      id: 163,
      difficulty: 'Medium',
      question: 'What is 324 ÷ 18?',
      hint: 'Divide 324 by 18.',
      explanation: '324 ÷ 18 = 18.',
      answer: 18,
    },
    {
      category: 'Arithmetic Challenges',
      id: 164,
      difficulty: 'Hard',
      question: 'What is 45% of 200?',
      hint: 'Multiply 200 by 0.45.',
      explanation: '45% of 200 is 200 × 0.45 = 90.',
      answer: 90,
    },
    {
      category: 'Logic Puzzles',
      id: 165,
      difficulty: 'Easy',
      question: 'If 6 oranges cost $18, how much does 1 orange cost?',
      hint: 'Divide the total cost by the number of oranges.',
      explanation: '18 ÷ 6 = $3 per orange.',
      answer: 3,
    },
    {
      category: 'Logic Puzzles',
      id: 166,
      difficulty: 'Medium',
      question:
        'If 8 workers can build a wall in 12 days, how many days will it take 16 workers to build the same wall?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '8 workers × 12 days = 16 workers × x days. x = 6 days.',
      answer: 6,
    },
    {
      category: 'Logic Puzzles',
      id: 167,
      difficulty: 'Hard',
      question: 'If 3^x = 81, what is the value of x?',
      hint: 'Express 81 as a power of 3.',
      explanation: '81 = 3^4, so x = 4.',
      answer: 4,
    },
    {
      category: 'Geometry',
      id: 168,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 9?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 9^2 = 81.',
      answer: 81,
    },
    {
      category: 'Geometry',
      id: 169,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 15? (Use π = 3.14)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × 3.14 × 15 = 94.2.',
      answer: 94,
    },
    {
      category: 'Geometry',
      id: 170,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 12 and height 9?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (12 × 9) ÷ 2 = 54.',
      answer: 54,
    },
    {
      category: 'Algebra',
      id: 171,
      difficulty: 'Easy',
      question: 'Solve for x: x + 12 = 24',
      hint: 'Subtract 12 from both sides.',
      explanation: 'x = 24 - 12, x = 12.',
      answer: 12,
    },
    {
      category: 'Algebra',
      id: 172,
      difficulty: 'Medium',
      question: 'Solve for x: 6x - 18 = 36',
      hint: 'Add 18 to both sides, then divide by 6.',
      explanation: '6x = 36 + 18, 6x = 54, x = 9.',
      answer: 9,
    },
    {
      category: 'Algebra',
      id: 173,
      difficulty: 'Hard',
      question: 'Solve for x: 5(x - 6) = 45',
      hint: 'Divide both sides by 5, then add 6.',
      explanation: 'x - 6 = 9, x = 9 + 6, x = 15.',
      answer: 15,
    },
    {
      category: 'Fractions',
      id: 174,
      difficulty: 'Easy',
      question: 'What is 1/5 of 30?',
      hint: 'Multiply 30 by 1/5.',
      explanation: '1/5 of 30 is 30 × 1/5 = 6.',
      answer: 6,
    },
    {
      category: 'Fractions',
      id: 175,
      difficulty: 'Medium',
      question: 'What is 2/3 of 45?',
      hint: 'Multiply 45 by 2/3.',
      explanation: '2/3 of 45 is 45 × 2/3 = 30.',
      answer: 30,
    },
    {
      category: 'Fractions',
      id: 176,
      difficulty: 'Hard',
      question: 'What is 4/5 of 100?',
      hint: 'Multiply 100 by 4/5.',
      explanation: '4/5 of 100 is 100 × 4/5 = 80.',
      answer: 80,
    },
    {
      category: 'Decimals',
      id: 177,
      difficulty: 'Easy',
      question: 'What is 0.6 × 50?',
      hint: 'Multiply 0.6 by 50.',
      explanation: '0.6 × 50 = 30.',
      answer: 30,
    },
    {
      category: 'Decimals',
      id: 178,
      difficulty: 'Medium',
      question: 'What is 0.9 × 20?',
      hint: 'Multiply 0.9 by 20.',
      explanation: '0.9 × 20 = 18.',
      answer: 18,
    },
    {
      category: 'Decimals',
      id: 179,
      difficulty: 'Hard',
      question: 'What is 0.125 × 160?',
      hint: 'Multiply 0.125 by 160.',
      explanation: '0.125 × 160 = 20.',
      answer: 20,
    },
    {
      category: 'Word Problems',
      id: 180,
      difficulty: 'Easy',
      question:
        'If a box contains 50 candies and you eat 20, how many candies are left?',
      hint: 'Subtract 20 from 50.',
      explanation: '50 - 20 = 30 candies are left.',
      answer: 30,
    },
    {
      category: 'Word Problems',
      id: 181,
      difficulty: 'Medium',
      question: 'A car travels 360 km in 6 hours. What is its speed in km/h?',
      hint: 'Speed = Distance ÷ Time.',
      explanation: 'Speed = 360 km ÷ 6 hours = 60 km/h.',
      answer: 60,
    },
    {
      category: 'Word Problems',
      id: 182,
      difficulty: 'Hard',
      question:
        'A rectangle has a length of 25 and a width of 6. What is its perimeter?',
      hint: 'Perimeter = 2 × (length + width).',
      explanation: 'Perimeter = 2 × (25 + 6) = 62.',
      answer: 62,
    },
    {
      category: 'Probability',
      id: 183,
      difficulty: 'Easy',
      question: 'What is the probability of rolling a 5 on a 6-sided die?',
      hint: 'There is 1 favorable outcome out of 6.',
      explanation: 'Probability = 1/6.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 184,
      difficulty: 'Medium',
      question:
        'What is the probability of drawing a spade from a standard deck of 52 cards?',
      hint: 'There are 13 spades out of 52.',
      explanation: 'Probability = 13/52 = 1/4.',
      answer: 1,
    },
    {
      category: 'Probability',
      id: 185,
      difficulty: 'Hard',
      question:
        'What is the probability of rolling a number greater than 3 on a 6-sided die?',
      hint: 'Favorable outcomes are 4, 5, and 6.',
      explanation: 'Probability = 3/6 = 1/2.',
      answer: 1,
    },
    {
      category: 'Number Puzzles',
      id: 186,
      difficulty: 'Easy',
      question: 'What is the next number in the sequence? 12, 24, 36, 48, ?',
      hint: 'Each number increases by 12.',
      explanation:
        'The sequence increases by 12 each time. The next number is 60.',
      answer: 60,
    },
    {
      category: 'Number Puzzles',
      id: 187,
      difficulty: 'Medium',
      question: 'Find the missing number: 5, 15, 45, 135, ?',
      hint: 'Each number is multiplied by 3.',
      explanation:
        'The sequence is 5, 15, 45, 135, 405. The missing number is 405.',
      answer: 405,
    },
    {
      category: 'Number Puzzles',
      id: 188,
      difficulty: 'Hard',
      question: 'What is the next number in the sequence? 4, 8, 16, 32, 64, ?',
      hint: 'Each number is multiplied by 2.',
      explanation:
        'The sequence is 4, 8, 16, 32, 64, 128. The next number is 128.',
      answer: 128,
    },
    {
      category: 'Arithmetic Challenges',
      id: 189,
      difficulty: 'Easy',
      question: 'What is 9 × 8?',
      hint: 'Multiply 9 by 8.',
      explanation: '9 × 8 = 72.',
      answer: 72,
    },
    {
      category: 'Arithmetic Challenges',
      id: 190,
      difficulty: 'Medium',
      question: 'What is 400 ÷ 20?',
      hint: 'Divide 400 by 20.',
      explanation: '400 ÷ 20 = 20.',
      answer: 20,
    },
    {
      category: 'Arithmetic Challenges',
      id: 191,
      difficulty: 'Hard',
      question: 'What is 50% of 180?',
      hint: 'Multiply 180 by 0.50.',
      explanation: '50% of 180 is 180 × 0.50 = 90.',
      answer: 90,
    },
    {
      category: 'Logic Puzzles',
      id: 192,
      difficulty: 'Easy',
      question: 'If 7 apples cost $21, how much does 1 apple cost?',
      hint: 'Divide the total cost by the number of apples.',
      explanation: '21 ÷ 7 = $3 per apple.',
      answer: 3,
    },
    {
      category: 'Logic Puzzles',
      id: 193,
      difficulty: 'Medium',
      question:
        'If 10 workers can build a wall in 15 days, how many days will it take 20 workers to build the same wall?',
      hint: 'More workers mean fewer days. Use inverse proportion.',
      explanation: '10 workers × 15 days = 20 workers × x days. x = 7.5 days.',
      answer: 7,
    },
    {
      category: 'Logic Puzzles',
      id: 194,
      difficulty: 'Hard',
      question: 'If 4^x = 256, what is the value of x?',
      hint: 'Express 256 as a power of 4.',
      explanation: '256 = 4^4, so x = 4.',
      answer: 4,
    },
    {
      category: 'Geometry',
      id: 195,
      difficulty: 'Easy',
      question: 'What is the area of a square with side length 11?',
      hint: 'Area of a square = side length^2.',
      explanation: 'Area = 11^2 = 121.',
      answer: 121,
    },
    {
      category: 'Geometry',
      id: 196,
      difficulty: 'Medium',
      question:
        'What is the circumference of a circle with radius 18? (Use π = 3.14)',
      hint: 'Circumference = 2πr.',
      explanation: 'Circumference = 2 × 3.14 × 18 = 113.04.',
      answer: 113,
    },
    {
      category: 'Geometry',
      id: 197,
      difficulty: 'Hard',
      question: 'What is the area of a triangle with base 14 and height 10?',
      hint: 'Area of a triangle = (base × height) ÷ 2.',
      explanation: 'Area = (14 × 10) ÷ 2 = 70.',
      answer: 70,
    },
    {
      category: 'Algebra',
      id: 198,
      difficulty: 'Easy',
      question: 'Solve for x: x + 15 = 30',
      hint: 'Subtract 15 from both sides.',
      explanation: 'x = 30 - 15, x = 15.',
      answer: 15,
    },
    {
      category: 'Algebra',
      id: 199,
      difficulty: 'Medium',
      question: 'Solve for x: 7x - 21 = 42',
      hint: 'Add 21 to both sides, then divide by 7.',
      explanation: '7x = 42 + 21, 7x = 63, x = 9.',
      answer: 9,
    },
    {
      category: 'Algebra',
      id: 200,
      difficulty: 'Hard',
      question: 'Solve for x: 6(x - 7) = 54',
      hint: 'Divide both sides by 6, then add 7.',
      explanation: 'x - 7 = 9, x = 9 + 7, x = 16.',
      answer: 16,
    },
  ],
};
